### DISCUSSION TITLE
CSS Selector for outer margin

### DISCUSSION THREAD

**Discussion by iLiranS** [zen-browser/desktop#1365] [Q&A]
Hi, I am trying to hide completely the margin in compact mode (something close to full screen experience)
I am kind of rusty in CSS, and I am not sure the structure in Zen browser.
Up to the previous update (a.39) this CSS block did the work
```css @media (-moz-bool-pref: "zen.view.compact") {
    :root:not([inDOMFullscreen="true"]):not([chromehidden~="location"]):not([chromehidden~="toolbar"]) {
      & #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
        margin: 0 !important;
        border-radius: 0 !important;
      }
    }
  }
```
I don't know now how to manipulate the border now, it only affects the radius, but the margin seems to be coming from other element.
