### DISCUSSION TITLE
How to display only tab icons in sidebar

### DISCUSSION THREAD

**Discussion by krisMG21** [zen-browser/desktop#3273] [Q&A]
I have my tabs as a side bar, and previously they were very compact, only displaying the icon. I don't know if it's because an update or I changed it accidentally, but I cannot find a way to change it back

**Comment by dosubot** [comment]
Hey @krisMG21! I'm here to help you with any bugs, questions, or contributions. Let's tackle this together!


To display only tab icons in the sidebar, you can modify the CSS to hide the tab labels and ensure that only the icons are visible. Here is a CSS snippet that you can use:

```css
#tabbrowser-tabs .tabbrowser-tab .tab-content {
    display: flex;
    align-content: center;
    justify-content: center;
    padding: 0 !important;
}

#tabbrowser-tabs .tabbrowser-tab .tab-label-container {
    display: none !important;
}
```

Additionally, you can use the following CSS for a more compact tab display:

```css
@container tab-container (max-width: 44px) {
    .tab-label-container {
        display: none !important;
    }
    .tab-content {
        justify-content: space-around !important;
    }
    .tab-close-button {
        display: none !important;
    }
}
```

This will hide the tab labels and ensure that only the tab icons are displayed in the sidebar <sup>[[1]](https://github.com/zen-browser/desktop/blob/dev/src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css)</sup><sup>[[2]](https://github.com/zen-browser/desktop/blob/dev/src/browser/base/content/zen-styles/zen-tabs/horizontal-tabs.css)</sup>. 

Alternatively, you can check the Zen Browser's settings for a preference that allows toggling between icon-only and full tab display. This is controlled by the checkbox with the ID `zenWorkspacesDisplayAsIconStrip`, associated with the preference `zen.workspaces.show-icon-strip` <sup>[[3]](https://github.com/zen-browser/desktop/blob/dev/src/browser/components/preferences/zenTabsManagement.inc.xhtml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
