### DISCUSSION TITLE
Bookmarks dissapear in fullscreen

### DISCUSSION THREAD

**Discussion by LordEnder-Kitty** [zen-browser/desktop#3321] [Ideas]
I tested and it's the same on normal Firefox so I wont report it as a bug on here but I noticed that the bookmarks disappear when you press f11 and enter fullscreen. This happens both in and out of compact mode with the top bar hidden.

**Comment by dosubot** [comment]
Hey @LordEnder-Kitty! I'm here to help you out with any bugs, questions, or contributions you have in mind. Let's tackle this together!


The disappearance of bookmarks in fullscreen mode is due to a specific CSS rule that hides toolbars when entering fullscreen. The rule is:

```css
:root[inFullscreen]:not([macOSNativeFullscreen]) toolbar:not([fullscreentoolbar=true]):not(.zen-dont-hide-on-fullscreen) {
  visibility: collapse;
}
```

This rule applies to toolbars, including the bookmarks bar, when the browser is in fullscreen mode, unless certain conditions are met (like having the `fullscreentoolbar` attribute set to `true` or the toolbar having the `zen-dont-hide-on-fullscreen` class) <sup>[[1]](https://github.com/zen-browser/desktop/blob/dev/src/browser/base/content/zen-styles/zen-toolbar.css)</sup><sup>[[2]](https://github.com/zen-browser/desktop/blob/dev/src/browser/themes/shared/tabbrowser/fullscreen-and-pointerlock-css.patch)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
