### DISCUSSION TITLE
How to set a custom image as the tab sidebar background?

### DISCUSSION THREAD

**Discussion by vavakado** [zen-browser/desktop#3338] [Q&A] [answered]
I suppose it's possible using userChrome or userContent.css

**Comment by dosubot** [comment]
Hey @vavakado! I'm here to help you out with any bugs, questions, or contributions you might have. Let's tackle this together!


To set a custom image as the tab sidebar background using `userChrome.css` or `userContent.css`, you can use the `background-image` CSS property. Here's a basic example of how you might do this in `userChrome.css`:

```css
#vertical-pinned-tabs-container {
    background-image: url("path/to/your/image.png");
    background-size: cover; /* Adjusts the image to cover the entire area */
    background-repeat: no-repeat; /* Prevents the image from repeating */
    background-position: center; /* Centers the image */
}
```

Replace `"path/to/your/image.png"` with the actual path to your image file. This CSS targets the `#vertical-pinned-tabs-container` element, which is part of the tab sidebar <sup>[[1]](https://github.com/zen-browser/desktop/blob/dev/src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by vavakado** [comment, marked as answer]
It didn't work however I managed to change the background of the whole sidebar using this code

```css
#tabbrowser-tabs {
  background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),
    url("wallhaven-rd9jpq.png") !important;
  background-size: cover !important;
  background-repeat: no-repeat !important;
  background-position: center !important;
}
```
