### DISCUSSION TITLE
How can we just expand the search bar instead of it floating.

### DISCUSSION THREAD

**Discussion by Ritwik-Sh** [zen-browser/desktop#3387] [Q&A]
I have Zen Twilight installed, and dont like the floating search bar. is there a way to change it to what Maubg showed it yet?

I want to get something like this
![Screenshot_2024-12-05-07-26-10-365-edit_com.reddit.frontpage.jpg](https://github.com/user-attachments/assets/d3c71b15-4464-4237-b846-af7e85da0828)

**Comment by dosubot** [comment]
Hey there, @RitwikSHS10! 👋 I'm here to help you with any bugs, questions, or contributions you might have. I'm Dosu, a bot designed to assist you while waiting for a human maintainer.


To expand the search bar in Zen Twilight instead of having it float, you can modify the CSS for the `#urlbar` element. Here's how you can do it:

1. Locate the CSS rule for `#urlbar[breakout-extend='true']`.
2. Remove or adjust the properties that set the `position` to `absolute` and control the `top`, `left`, and `transform` properties.

Here's an example of how you might modify the CSS:

```css
#urlbar[breakout-extend='true'] {
  z-index: 1000;
  min-width: 600px;
  top: 0 !important;
  --urlbar-container-height: 55px !important;
  --urlbar-margin-inline: 10px !important;

  & #urlbar-background {
    background: var(--zen-branding-bg) !important;
    backdrop-filter: blur(10px);
    border: 1px solid var(--arrowpanel-border-color) !important;
  }

  & #identity-box {
    margin-right: var(--urlbar-margin-inline);
  }

  :root[zen-right-side='true'] & {
    right: 0;
  }

  /* Remove the following block to prevent floating */
  /* @media not (-moz-bool-pref: 'zen.view.compact') {
    max-width: 45%;
    min-width: 45%;
    position: absolute;

    top: calc(var(--zen-toolbar-height) * 4) !important;
    left: 50%;
    transform: translateX(-50%);
  } */
}
```

By removing the block that sets the `position` to `absolute` and adjusts the `top`, `left`, and `transform` properties, the search bar will no longer float and should expand as desired <sup>[[1]](https://github.com/zen-browser/desktop/blob/dev/src/browser/base/content/zen-styles/zen-urlbar.css)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
