### DISCUSSION TITLE
Add a setting to disable the sidebar transparency / blur

### DISCUSSION THREAD

**Discussion by MoltenMonster** [zen-browser/desktop#3397] [Ideas]
Its an opinionated aesthetic choice with some users prefer to be turned off, especially to fully see color themes. For now here's a userChrome CSS workaround:

```css
  #zen-main-app-wrapper,  #zen-appcontent-wrapper,  #zen-sidebar-splitter {
    appearance: unset !important;
  }
```
