### DISCUSSION TITLE
Mechanism to declare firefox extensions and zen mods that every profile should have

### DISCUSSION THREAD

**Discussion by luisnquin** [zen-browser/desktop#4097] [Ideas]
As long as I know, [most of the Chromium-based browsers](https://github.com/nix-community/home-manager/blob/10e99c43cdf4a0713b4e81d90691d22c6a58bdf2/modules/programs/chromium.nix#L7) has a [mechanism to specify extensions that should be installed on the browser](https://developer.chrome.com/docs/extensions/mv2/external-extensions#prereqs).

So I think that a part of your users(mostly those who have dot config files or uses Nix) will benefit from this proposal.

They could have some config options to declaratively and reproducibly communicate to the browser about some things that need to be installed or uninstalled across all the browser profiles, that's the behavior in Chromium(at least in Brave and Vivaldi).

From Linux user that does not uses Nix they could have a dot file like this:

```toml
# path/to/zen/config.toml

[global]
# Links to https://zen-browser.app/mods/*
mods = [
  "c8f20381-388a-4b67-b640-eaa539355ea4", # Right On Hover Sidebar
  "ef16716a-58dc-42d4-99f8-b1667d32247d", # F1
  "2e3369c7-e450-46ba-8794-75ccb0de5e48", # Now playing indicator
  "c6813222-6571-4ba6-8faf-58f3343324f6" # Disable Rounded Corners
]

# Links to https://addons.mozilla.org/en-US/firefox/addon/*
addons = [
  "wappalyzer"
]

# you could even add keybindings config here and the browser will be aware of that... :)
```

And those **zen mods** and **firefox addons** will be automatically managed by the browser.

From a Nix-user perspective, this could allow me to declare my configuration like in the following snippet:

```nix
{
  programs.zen = {
    enable = true;
    package = pkgs.zen-twilight;

    # Links to https://zen-browser.app/mods/*
    mods = [
      "c8f20381-388a-4b67-b640-eaa539355ea4" # Right On Hover Sidebar
      "ef16716a-58dc-42d4-99f8-b1667d32247d" # F1
      "2e3369c7-e450-46ba-8794-75ccb0de5e48" # Now playing indicator
      "c6813222-6571-4ba6-8faf-58f3343324f6" # Disable Rounded Corners
    ];

    # Links to https://addons.mozilla.org/en-US/firefox/addon/*
    addons = [
      "wappalyzer"
    ];
  };
}
```

BTW I'm currently maintaining [this flake](https://github.com/0xc000022070/zen-browser-flake) that distributes the browser in Nix-compatible systems.

I would love to have this available. By the time I write this... happy new year's evening! :)
