### DISCUSSION TITLE
Vertically center the popout search/address bar?

### DISCUSSION THREAD

**Discussion by kvnxiao** [zen-browser/desktop#4204] [General]
Is there a way to vertically center the search bar rather than it being hovering close to the top of the screen?

![image](https://github.com/user-attachments/assets/1b20a53a-afee-4f8e-a55b-823feb3982af)

**Comment by 12th-devs** [comment]
@kvnxiao you can make some custom css, when I have the chance I will get you the css for my URL bar

**Reply by dopmore** [reply]
@Anoms12 what have you changed in your custom css?

**Reply by kvnxiao** [reply]
I figured it out on my own, you can use something like
```css
#urlbar[open][zen-floating-urlbar='true'] {
  top: calc(40vh - var(--zen-toolbar-height) * 1) !important;
}
```
in your userChrome.css
