### DISCUSSION TITLE
Potential performance improvement for Zen on macOS in some circumstances, possibly

### DISCUSSION THREAD

**Discussion by different55** [zen-browser/desktop#4372] [Ideas]
In `zen-browser-ui.css`, Zen does this for macOS:

```css
@supports (-moz-osx-font-smoothing: auto) {
  #zen-main-app-wrapper,
  #zen-appcontent-wrapper,
  #zen-sidebar-splitter {
    appearance: -moz-window-titlebar !important;
  }
}
```

This is cool and good. When there are no gradients applied to the current workspace, this makes Zen's UI take on the native macOS grainy glass material:

<img width="800" alt="Screenshot 2025-01-15 at 4 46 12 PM" src="https://github.com/user-attachments/assets/89aed3e0-1b11-44f2-85cf-aa4591d57e58" />

But if there is a gradient applied, above around opacity/contrast 0.5 it becomes unnoticeable, and when contrast/opacity is 1 there's no impact at all. Except to performance.

For me and On My Machine™, whenever the appearance is set on these elements to -moz-window-titlebar, there's a noticeable hit to scrolling performance. Continuous scroll behavior seems fine enough, it's just a skip of a few hundred milliseconds at the first initial moment of scrolling if more than a second or two has passed since the last scroll.

Maybe there's a more direct way to keep the visuals active always without taking the hit, but if not, opportunistically unsetting that rule seems to make Zen more fluid, again, On My Machine™.
