### DISCUSSION TITLE
Pinned Extensions in Single Toolbar Layout

### DISCUSSION THREAD

**Discussion by sillvva** [zen-browser/desktop#4775] [Ideas]
Right now, the pinned extensions don't work in Single Toolbar layout. They're simply hidden in the extension menu again. It would be nice if they could be displayed between the URL and Essentials as a grid like they are in Arc Browser.

![CleanShot 2025-01-31 at 08 38 35@2x](https://github.com/user-attachments/assets/2af3c3fa-61cd-4a91-90a0-500c5cb3b89d)

I'd be satisfied with the pinned extensions being either above or below the URL bar.

![image](https://github.com/user-attachments/assets/a6ca1792-1dd7-4496-8877-8e54668b24f5)

**Comment by kud3n013** [comment]
THISS!!!

**Comment by Extroonie** [comment]
Absolutely agree!

For now, those interested can use [this custom CSS](https://github.com/YashjitPal/Arc-2.0/blob/57306dffba80f9a929c200e506b589d913efe16b/Arc%202.0/Chrome%20CSS/extensions.css#L1-L74). [Learn how to customize CSS](https://docs.zen-browser.app/guides/live-editing).

If you want to display extension badges, you may need to tweak it slightly by adding:
```css
.toolbarbutton-badge {
    display: flex !important; /* Restores extension badges */
    box-shadow: none !important; /* Removes unwanted borders */
    background-clip: content-box !important;
}
```  
The `display: flex !important;` rule restores extension badges, while `box-shadow` and `background-clip` help eliminate unwanted borders.
