### DISCUSSION TITLE
Revert pinned tabs staying in view as you scroll through the tabs

### DISCUSSION THREAD

**Discussion by Lu9-ST** [zen-browser/desktop#4810] [Ideas]
I'm a bit saddened with the latest update and how it made pinned tabs basically almost exactly like regular tabs just with a separation line. I use the mod that reverts pinned tabs to their previous "side by side blocks" look (which is now used by Essentials), meaning screen space isn't a problem, while having Esesntials at the bottom. I still would prefer to have the pinned tabs in view (so, yknow, *pinned*) even when I have many tabs opened and scrolled all the way to the bottom.

I know that this is *possibly* to accomodate the new default of having new tabs always at the top, but, it's even been giving me problems (most of which were already addressed in builds from after the time of this post)

I would at least like the option (maybe a zen mod, if it can be done) to have the pinned tabs stay in view.

**Comment by Abdullah16M** [comment]
+1

Pinned tabs should always stay in view (we may add a scroller to them but their container should always stay at the top separate from regular tabs), even in horizontal browsers pinned tabs are always visible, having pinned tabs out of view is counterintuitive to its main function. Old users may not be affected as they will revert the changes but new users will think its ridiculous.

In the changelog of 1.7.3b:
"Pinned tabs AND normal tabs will now scroll together in order to increase visibility", the main point of pinned tabs is visibility at all times at the cost of regular tabs, revoking this makes them useless.

**Comment by guandesoledad** [comment]
+1

**Comment by Lu9-ST** [comment]
Bumping this because I was trying to come up with some custom userChrome CSS to perhaps "reviving" this, but don't have any idea of how that's gonna work.
A simple `position: sticky;` won't do, of course. The pinned tabs div was placed *inside* the container where the regular tabs reside.
So who knows... anyone who might know a bit more? :P

**Comment by roubilibo** [comment]
+1
make pinned tab pinned again

**Comment by MaxHart828** [comment]
Yes, bring back pinned tabs that pin.

**Comment by sporocyst** [comment]
A tentative code that may fit the need to pin the pinned tabs

```
#vertical-pinned-tabs-container {
position: sticky !important;
top: 0;
z-index: 5;
}

#zen-browser-tabs-container {height: 100%;}
#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
backdrop-filter: blur(10px);
}
```

Any feedback is welcomed, so that maybe we can make it a mod.
(tested on 1.9.1b windows version. compatible with SuperPin v1.4.5)

**Reply by Lu9-ST** [reply]
nice fix! the blur trickery however only works if the current user/workspace theme (set in "change theme colors") has a high set contrast, or in compact mode
there should be another way to make this work...
i added this to make it work better with SuperPin: 
```CSS
#vertical-pinned-tabs-container {
position: sticky !important;
top: 0;
z-index: 5;
.tabbrowser-tab .tab-background {
    background: var(--zen-toolbar-element-bg) !important;
  }
.tabbrowser-tab:hover .tab-background {
    background: var(--tab-selected-bgcolor) !important;
  }
}

#zen-browser-tabs-container {height: 100%;}
#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
backdrop-filter: blur(10px);
}
```

EDIT: by the way, after a bit of scrolling (likely after it scrolls exactly the screen height amount) it stops working.

**Reply by sporocyst** [reply]
Yet another piece of code with imporvement
```
#zen-tabs-wrapper {position: static !important;}
#zen-browser-tabs-container {
  position: static !important;
}
#vertical-pinned-tabs-container {position: static !important;}

#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
background: var(--zen-main-browser-background) !important;
z-index: 5;
width: 100%;
.tabbrowser-tab .tab-background {
    background: var(--zen-toolbar-element-bg) !important;
  }
.tabbrowser-tab:hover .tab-background {
    background: var(--tab-selected-bgcolor) !important;
  }
}

#tabbrowser-arrowscrollbox {position: relative !important;}
```

or another approach
```
#zen-browser-tabs-container {height: fit-content;}
#vertical-pinned-tabs-container {position: sticky !important; top: 0; z-index: 1;}
#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
background: var(--zen-main-browser-background) !important;
.tabbrowser-tab .tab-background {
    background: var(--zen-toolbar-element-bg) !important;
  }
.tabbrowser-tab:hover .tab-background {
    background: var(--tab-selected-bgcolor) !important;
  }
}
#tabbrowser-arrowscrollbox {height: fit-content; }
#tabbrowser-arrowscrollbox > .zen-workspace-tabs-section {position: relative !important;}
```

Not sure which is better

**Reply by Lu9-ST** [reply]
first one seems okay to me, the second one for some reason makes *other* workspaces too long and *unable* to scroll for some reason (in compact mode) and now the regular tabs' text is visible behind them... but it's progress!
also, in workspaces with applied custom colors, the background of the pinned tabs area will look weird, especially in compact mode.
just remove the `background: var(--zen-main-browser-background) !important;` part, as that unfortunately isn't helping much with fixing the text under the buttons, and for now, reenable the blur thing as at least that does work in compact mode.

And here it is so far:
```CSS
#zen-tabs-wrapper {position: static !important;}
#zen-browser-tabs-container {
  position: static !important;
}
#vertical-pinned-tabs-container {position: static !important;}

#vertical-pinned-tabs-container > .zen-workspace-tabs-section {

z-index: 5;
width: 100%;
.tabbrowser-tab .tab-background {
    background: var(--zen-toolbar-element-bg) !important;
  }
.tabbrowser-tab:hover .tab-background {
    background: var(--tab-selected-bgcolor) !important;
  }
}

#tabbrowser-arrowscrollbox {position: relative !important;}


#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
backdrop-filter: blur(10px);
}
```

only the background needs work at this point pretty much, but the "main functionality" seems to work properly now
