### DISCUSSION TITLE
Disable workspace switch animation (no delay)?

### DISCUSSION THREAD

**Discussion by niderhoff** [zen-browser/desktop#5016] [General]
When switching workspaces there is a 1/2 second delay until the tab of the new workspace is displayed.

Also there is a animation going on in the sidebar. How can I disable it and achieve instant switching?

**Comment by simon-ami** [comment]
Here's a `userChrome.css`-based workaround till it's officially supported:

Place this in your profile directory in the `chrome` folder as `userChrome.css` (or add to your existing file's rules) and enable `toolkit.legacyUserProfileCustomizations.stylesheets` in the `about:config`-preferences page:

```css
/* --- Disable workspace sliding animations --- */

zen-workspace {
  display: none !important;
  transform: none !important;
  transition: none !important;
}

zen-workspace:not([style*="translateX("]),
zen-workspace[style*="translateX(0%)"],
zen-workspace[style*="translateX(0px)"] {
  display: flex !important;
}

:root[animating-background] zen-workspace:last-of-type {
  display: flex !important;
}

:root[swipe-gesture] zen-workspace {
  display: none !important;
  transform: none !important;
}

:root[swipe-gesture] zen-workspace:last-of-type {
  display: flex !important;
}

:root[animating-background] .zen-sidebar-pinned-tabs,
:root[animating-background] #zen-sidebar-pinned-tabs,
:root[animating-background] [class*="pinned"],
:root[animating-background] [class*="essential"] {
  transform: none !important;
  transition: none !important;
}

:root[swipe-gesture] .zen-sidebar-pinned-tabs,
:root[swipe-gesture] #zen-sidebar-pinned-tabs,
:root[swipe-gesture] [class*="pinned"],
:root[swipe-gesture] [class*="essential"] {
  transform: none !important;
  transition: none !important;
}
```

You can find a more thorough guide on installation here if the above doesn't make sense to you: https://github.com/SimonB97/helpers/tree/master/universal/zen-browser-workspace-animation-disable

Edit:
Also, notice that there's a slight delay when switching to the first workspace in your list (which is NOT related to number of tabs btw). If you happen to find a fix for that, I'd be grateful for your PR or just a comment here about how you've done it!
