### DISCUSSION TITLE
Media player should follow / match custom theme color (gradient)

### DISCUSSION THREAD

**Discussion by sjclayton** [zen-browser/desktop#6720] [Ideas]
This should be pretty self-explanatory based on the title.

But I think it would be nice, if the media player background and maybe controls were coloured/tinted based on the user's custom theme colors / gradient. It would make things blend together in a much more smooth and attractive way.

**Comment by ParlDev** [comment]
That's a pretty good idea, right now it sticks out like a sore thumb against everything else, although I know some people like it to be that way... maybe a good in-between? I know that the seek-bar is already colored to match the theme, so the ability is definitely there.

**Reply by sjclayton** [reply]
I have it taken care of right now with custom CSS, but I definitely think it is something that should be done by default.

If you want to try it, add the following to your userChrome.css and adjust the color ratio to your liking. 
It only uses the primary color as basis for the change, so it does not take gradients into account right now.

```css
#zen-media-controls-toolbar > toolbaritem {
  background-color: color-mix(in srgb, var(--zen-colors-primary) 100%, black 55%) !important;
}
```
