### DISCUSSION TITLE
Red outline around the fields

### DISCUSSION THREAD

**Discussion by Lorg0n** [zen-browser/desktop#7941] [Q&A] [answered]
I switched from Chrome to Zen, having never used Firefox forks before. Why does this red border appear around some fields on different sites? I have it on different devices, with different extensions and themes, but the stroke is the same. It is definitely not created by the site itself. How to switch it off

OS: Win11
![image](https://github.com/user-attachments/assets/a6b14673-9f52-4c45-9448-1725e4d1b3aa)

**Comment by Lorg0n** [comment, marked as answer]
Solution:

1. Find the location of the Profile Folder (about:support -> Application Basics -> Profile Folder) and open it
2. Create chrome folder (Profiles\\\*\*\*\*\*\*.Default\\chrome)
3. Create a "userContent.css" file (\\chrome\\userContent.css) in the folder.
4. Write the code:
```css
input:focus,
textarea:focus,
button:focus {
  outline: none !important;
}

input::-moz-focus-inner,
textarea::-moz-focus-inner,
button::-moz-focus-inner {
  border: 0 !important;
  padding: 0 !important;
}
```
5. Switch "toolkit.legacyUserProfileCustomisations.stylesheets" to true in the settings (about:config)
6. Restart the browser
