### DISCUSSION TITLE
It'd be great for then to have proper initial titles when opening new windows

### DISCUSSION THREAD

**Discussion by bielarusajed** [zen-browser/desktop#7947] [Ideas]
Hi! I use a tiling WM on Linux (hyprland in my case) and it bugs me a bit when extensions open in new window, and it automatically tiled. I'd like to disable that behavior in my WM config, but I can't properly match the window, because initially it has the same class and the same title, as the main window:

```
Window 6430083d7500 -> Extension: (Bitwarden Password Manager) - Bitwarden — Zen Browser:
        mapped: 1
        hidden: 0
        at: 1445,9
        size: 1426,927
        workspace: 1 (1)
        floating: 0
        pseudo: 0
        monitor: 0
        class: zen
        title: Extension: (Bitwarden Password Manager) - Bitwarden — Zen Browser
        initialClass: zen
        initialTitle: Zen Browser
        pid: 15261
        xwayland: 0
        pinned: 0
        fullscreen: 0
        fullscreenClient: 0
        grouped: 0
        tags:
        swallowing: 0
        focusHistoryID: 2
        inhibitingIdle: 0

Window 643008201a70 -> New Discussion · zen-browser/desktop — Zen Browser:
        mapped: 1
        hidden: 0
        at: 9,9
        size: 1426,1864
        workspace: 1 (1)
        floating: 0
        pseudo: 0
        monitor: 0
        class: zen
        title: New Discussion · zen-browser/desktop — Zen Browser
        initialClass: zen
        initialTitle: Zen Browser
        pid: 15261
        xwayland: 0
        pinned: 0
        fullscreen: 0
        fullscreenClient: 0
        grouped: 0
        tags:
        swallowing: 0
        focusHistoryID: 1
        inhibitingIdle: 0
```

See, the bitwarden one is named `Extension: (Bitwarden Password Manager) - Bitwarden — Zen Browser`, and I thought I could match any zen window, that named `Extension:*`, but I can't, because its *initial title* was the default `Zen Browser`. Maybe it'd be possible to change the initial title or the initial class for the extensions windows?
