### DISCUSSION TITLE
Full Screen mode does not automatically enable Compact Mode

### DISCUSSION THREAD

**Discussion by mr-cheffy** [zen-browser/desktop#801] [Ideas]
### What happened?

When entering Full Screen mode, the sidebar (vertical tabs) and the top bar should automatically hide, allowing the website content to occupy the entire screen. However, the current behavior shows that both the sidebar and top bar remain visible until the user manually enables compact mode using a keyboard shortcut.

Expected Behavior:
Upon entering Full Screen mode, the sidebar (vertical tabs) and top bar should automatically hide, allowing only the website content to be displayed across the entire page.

Current Behavior:
In Full Screen mode, the sidebar and top bar remain visible until compact mode is manually activated by the user.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low, Enhancement

### What platform are you seeing the problem on?

Linux

 
 ~ _Created automatically from issue: https://github.com/zen-browser/desktop/issues/558_

**Comment by alex-pex** [comment]
That's exactly what I was looking for. I'm on Mac OS and going fullscreen I expected compact mode to be enabled, or at least a setting to activate this behavior.

Not a deal breaker, but it would make the experience so much smoother!

**Comment by alexisdechiara** [comment]
Yes, fullscreen means that you can focus solely on the content you're watching by removing all superfluous browser interfaces. I love using it on Twitch in studio mode.

There's another discussion about removing the top bar [here](https://github.com/zen-browser/desktop/discussions/3131#discussion-7522378), it might be a good idea to have an option to automatically activate compact mode to satisfy everyone

**Comment by sduquette-devolutions** [comment]
Hard agree, fullscreen should show only the current tab content like on Firefox. I really like to put pages in full screen when I want to read long articles as it removes visual distractions on screen.

**Comment by skdza** [comment]
Fullscreen means full. sreen. I really don't understand why they didn't make it hide the sidebar, topbar and the border. Odd stuff
+1

**Comment by ParlDev** [comment]
+1
YES! I feel like this should absolutely be a thing and I have no clue why it hasn't been implemented yet.

btw, I know someone will also not like it, so make sure to make a setting for it whenever someone programs this in.

**Comment by joeytwiddle** [comment]
Yes, fullscreen should hide the address bar, the tabs, and the sidebar, so that the page content fully fills the screen.

**Reply by Lampe2020** [reply]
I've now spent an hour or so in Zen's chrome debugger and created this CSS that you can put in `userChrome.css`:   
```CSS
:root[inFullscreen=true] tabpanels#tabbrowser-tabpanels,
:root[inFullscreen=true] #zen-tabbox-wrapper {
    position: fixed !important;
    top: 0 !important;
    left: 0 !important;
    right: 0 !important;
    bottom: 0 !important;
    margin: 0 !important;
}
    
:root[inFullscreen=true] toolbox#navigator-toolbox,
:root[inFullscreen=true] div#zen-appcontent-navbar-wrapper {
    display: none !important;
    width: 0 !important;
    height: 0 !important;
}

#main-window[chromehidden*="toolbar"] #nav-bar {
  visibility: collapse;
}
```

For some weird reason though it only works while the developer toolbox window is open…
