### DISCUSSION TITLE
zen.workspaces.show-workspace-indicator no longer works

### DISCUSSION THREAD

**Discussion by ypurpl** [zen-browser/desktop#8058] [Q&A] [answered]
`zen.workspaces.show-workspace-indicator` used to hide the indicator, latest update now it doesn't

**Comment by barbedo** [comment]
I just noticed that the indicator also (re)appeared here after the latest update...

The option got removed by https://github.com/zen-browser/desktop/commit/a7d0719877d34a3cdc4b82ce013b7e7bdbaa4cf6 a few days ago. I have no idea why.

I don't use workspaces, so I just added the option back in my `userChrome.css`:

```css
/*
 * Workaround for 'zen.workspaces.show-workspace-indicator' being suddenly removed:
 * https://github.com/zen-browser/desktop/commit/a7d0719877d34a3cdc4b82ce013b7e7bdbaa4cf6
 * Add 'zen.workspaces.show-workspace-indicator=false' to about:config if not defined.
 */
@media not -moz-pref('zen.workspaces.show-workspace-indicator') {
  #zen-current-workspace-indicator-container {
    display: none !important;
  }
}
```

**Reply by ypurpl** [reply]
Good enough workaround for now

**Reply by nms808** [reply]
Agreed, but we should have a dedicated switch for this in the main system menu, especially for those of us that will never use them. I have session addons for that which I keep disabled until needed which is rarely if ever.

**Reply by sinlessone** [reply]
Why can't we just have an option to have it somewhere hidden if it really has to be somewhere, like the application menu, it is really annoying for someone who doesn't use it (this work around doesn't work now)

**Reply by s3bba** [reply]
This works for me:
```css
.zen-current-workspace-indicator {
  display: none !important;
}
```

**Reply by dockerisedDan** [reply]
Can confirm that @s3bba solution works after the recent update

**Reply by ccrsxx** [reply]
Yup they changed the selector name. It works again now `.zen-current-workspace-indicator`

**Reply by Geobert** [reply]
Broken again in 1.14

**Reply by nms808** [reply]
> Broken again in 1.14

.zen-current-workspace-indicator {
  display: none !important;
}

As reported above, adding this to userchrome.css still works. If, however, you are looking for any easy on/off switch that we SHOULD HAVE IN THE SETTINGS OR SIDEBAR MENU, well then yes, you are correct!

**Reply by Mr-Mamosa** [reply]
For those who are new here:
First search for 'about:support' on you search bar. Then look for Profile folder there and then click on openfolder it will open loaction in your folder. Now there will be a folder name Chrome and then if there is file name userChrome,.css file paste this code''

.zen-current-workspace-indicator {
  display: none !important;
}

if not create one and restart your browser.

**Comment by kashamalasha** [comment]
I got 
```css
/*
 * Workaround for 'zen.workspaces.show-workspace-indicator' being suddenly removed:
 * https://github.com/zen-browser/desktop/commit/a7d0719877d34a3cdc4b82ce013b7e7bdbaa4cf6
 * Add 'zen.workspaces.show-workspace-indicator=false' to about:config if not defined.
 */
@media not -moz-pref('zen.workspaces.show-workspace-indicator') {
  .zen-current-workspace-indicator {
    display: none !important;
  }
  #zen-current-workspace-indicator-container {
    display: none !important;
  }
}
```
and it doesn't work in `1.14.1b`

**Reply by ypurpl** [reply]
comment instead of posting an answer, i changed the right answer

**Comment by ypurpl** [comment, marked as answer]
older answer doesnt work, use this in `userChrome.css`: 
(make `chrome` folder in your profile and create the file if necessary)

```css
.zen-current-workspace-indicator {
  display: none !important;
}
```
 thanks to @s3bba 

if necessary set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true` in `about:config` if it doesnt work
