### DISCUSSION TITLE
New tab button should not be part of the scrolling tabs on sidebar

### DISCUSSION THREAD

**Discussion by mr-cheffy** [zen-browser/desktop#806] [Ideas]
### What feature would you like to see?

Currently the New Tab button can be hidden if a lot of tabs are open and you scroll up. It should not do this and instead be achored on the sidebar on it's position. Either this or have it as an option (I personally see it as a bad thing).

### What platform are you seeing the problem on?

Windows

### Additional context

Scrolled down to the very bottom:
![image](https://github.com/user-attachments/assets/09f0b426-2042-4f98-95f4-485aa12b8b36)

Then, if I scroll a _little_ bit up:
![image](https://github.com/user-attachments/assets/4599e999-8a5f-4508-96c2-b60b5e35823a)

It get hidden because it currently scrolls with the open tabs on the sidebar.

Pls fix :)
 
 ~ _Created automatically from issue: https://github.com/zen-browser/desktop/issues/527_

**Comment by ovachiever** [comment]
I agree with this, poor UI decision; new tab button should be anchored within a container above the vertical tabs, or as part of the top of the vertical toolbar container.

**Comment by Doc-4** [comment]
I agree, any fixed UI placement would be preferable to being able to scroll the new tab button out of view.

**Comment by badjuice** [comment]
A *bit* off-topic but related:

I have now noticed that the pinned tabs also get hidden by scrolling down. On Microsoft Edge, when using vertical tabs, after pinning some tabs, these are preserved as fixed on the tab list so they are always reacheable.

I'm now finding myself having to scroll back up through a lot of tabs to get to the top ones. It kinda defeats the point of having them pinned 😅 I could just leave them as the first opened tabs and it would be the same. The pinning should make that difference.

What I mean (notice the scrollbar - I am scrolled a bit down):
![image](https://github.com/user-attachments/assets/53f65847-b1a6-4da1-9334-8ee85c7c0ff6)
This is on Microsoft Edge ☝🏽

Currently on Zen:
![image](https://github.com/user-attachments/assets/f1a535a9-a3a4-471f-84f7-7b59334ff21c)
Some of the tabs are hidden.

**Reply by Starry-AXQG** [reply]
> _有点_题外但相关：
> 
> 我现在注意到，向下滚动时，固定的标签页也会被隐藏。在 Microsoft Edge 上，使用垂直标签页时，固定某些标签页后，这些标签页在标签页列表中会保留为固定状态，因此始终可以访问它们。
> 
> 我现在发现自己得往上翻好多标签页才能找到最顶部的标签页。这有点违背了把它们固定的意义 😅 我可以直接把它们设为最先打开的标签页，效果应该一样。固定标签页应该能带来这种区别。
> 
> 我的意思是（注意滚动条 - 我向下滚动了一点）： ![image](https://private-user-images.githubusercontent.com/25462821/363994567-53f65847-b1a6-4da1-9334-8ee85c7c0ff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ4ODA3MDksIm5iZiI6MTc0NDg4MDQwOSwicGF0aCI6Ii8yNTQ2MjgyMS8zNjM5OTQ1NjctNTNmNjU4NDctYjFhNi00ZGExLTkzMzQtOGVlODVjN2MwZmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE3VDA5MDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNTY0OTMzMzA0ZWJmZjdlZjFhMzliYzc2NWU1MDJhYmQwY2Y3ZmRjY2E4ODc5ZjM5NGVkNmJmOTQ5NDNjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tTZDT9WWLYjhWgZDFo8St1FW4AwGhkBB-rpWnbkEGY0)这是在 Microsoft Edge 上☝🏽
> 
> 目前在 Zen 上： ![image](https://private-user-images.githubusercontent.com/25462821/363995412-f1a535a9-a3a4-471f-84f7-7b59334ff21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ4ODA3MDksIm5iZiI6MTc0NDg4MDQwOSwicGF0aCI6Ii8yNTQ2MjgyMS8zNjM5OTU0MTItZjFhNTM1YTktYTNhNC00NzFmLTg0ZjctN2I1OTMzNGZmMjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE3VDA5MDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NmI0NWMyNGIyYzEzNWNkYTM4YjA5NTgxMDAwZWQ2ZDMxMzdlMWY5M2VhZWFjZGYxN2U2YjU0MjVkYTRlMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7aPADH3qIsgc--xtebmzejTeqYREUD33Rz-NH_KmYQ4)一些标签被隐藏了。

Yes. But you have tried`Add to Essentials`?This function is truly equivalent to the fixed tabs of other browsers

**Comment by azulika** [comment]
I agree. This must be implemented

**Reply by azulika** [reply]
I made a very rough workaround css. It won't work if "move the new tab button to the top" is enabled.
```css
#tabs-newtab-button {
    position: fixed;
    bottom: 70px;
    z-index: 100;
}

#tabs-newtab-button::before {
    content: '';
    display: block;
    height: 1px;
    background: light-dark(rgba(1, 1, 1, 0.075), rgba(255, 255, 255, 0.1));
    width: 100%;
    position: absolute;
    top: -8px;
    left: 50%;
    transform: translateX(-50%);
}

#tabbrowser-arrowscrollbox {
    padding-bottom: 50px;
}

hbox#tabbrowser-arrowscrollbox-periphery::before {
    display: none !important;
}

#tabbrowser-arrowscrollbox[orient="vertical"] {
    &[overflowing]:not([scrolledtoend]) {
        mask-image: none !important;
    }
}
```

**Reply by badjuice** [reply]
There has been added a separate scroll bar to each of the sections (pinned tabs and regular tabs) and the "New tab" button is not yet anchored to the bottom of the opened tabs list. 🤷🏽‍♀️

**Comment by Starry-AXQG** [comment]
Guys, I've tried some methods. It seems that I can't solve this problem well through third-party means at present. However, we can still select "New TAB" by using the shortcut key "Ctrl+T" or right-clicking on any TAB.
If you want to change the behavior of creating a new TAB page to opening a new page, please:`about:config`，search`zen.urlbar.replace-newtab`set as `false`

**Comment by Damglador** [comment]
A fix using userChrome.css:
```css
#tabbrowser-arrowscrollbox-periphery {
  position: sticky;
  top: 0;
  left: 0;
  bottom: 0;
  background-color: var(--zen-main-browser-background-toolbar);
  width: var(--zen-sidebar-width) - 5;
  z-index: 10;
}
```
It stays at the top or bottom (depending on Zen settings) when you scroll past it. The background may not match the theme though, I couldn't figure out how to do that properly.

**Comment by xSAVEQx** [comment]
I vibecoded a solution that sticks perfectly to both top and bottom (depending on Zen settings) and doesn't have any issues that the fixes above do. Unfortunately I had to hardcode color values (otherwise the button was either translucent or had an ugly background that doesn't match with the rest of Zen) though it can also be a positive as it allows for everyone to easily tweak its colors to their exact liking and theme.

### Instructions:
1. In the URL bar type in `about:config` and press Enter.
2. Click on `Accept the Risk and Continue`.
3. Using search bar on top, find flag `toolkit.legacyUserProfileCustomizations.stylesheets` and double click on it in order to change its value from false to true.
4. Now again in the URL bar type in `about:support` and press Enter.
5. Look for the `Application Basics` section and find a row with `Profile Folder`.
Click on `Open Folder`. This will open the folder where Zen Browser stores your user data.
6. In the directory which you just opened, create a new folder and name it `chrome`.
7. Download [userChrome.css](https://github.com/user-attachments/files/29868353/userChrome.css) and paste it into the chrome folder from previous step.
8. Restart Zen Browser and enjoy your sticky New Tab button.

#### The attached file contains:
```css
/*
 * Zen Browser - sticky New Tab button
 *
 * Placement follows Zen's setting:
 *   zen.view.show-newtab-button-top = true  -> top, above the tab list
 *   zen.view.show-newtab-button-top = false -> bottom, above workspaces
 */

@-moz-document url("chrome://browser/content/browser.xhtml") {
  :root {
    --uc-newtab-gap: 0px;
    --uc-newtab-edge-nudge: 0px;
    --uc-newtab-height: var(--tab-min-height, 32px);
    --uc-newtab-row-height: var(--uc-newtab-height);

    /* Solid colors for the button, interchangable RGB values */
    --uc-newtab-row-bg: rgb(31, 31, 31);
    --uc-newtab-button-bg: rgb(58, 58, 58);
    --uc-newtab-button-bg-hover: rgb(68, 68, 68);
  }

  #tabs-newtab-button,
  #vertical-tabs-newtab-button,
  #new-tab-button {
    display: none !important;
  }

  #tabbrowser-arrowscrollbox-periphery > #tabs-newtab-button {
    display: flex !important;
  }

  #tabbrowser-arrowscrollbox-periphery {
    position: sticky !important;
    top: auto !important;
    bottom: var(--uc-newtab-edge-nudge) !important;
    z-index: 2147483647 !important;
    isolation: isolate !important;
    overflow: visible !important;

    flex: 0 0 auto !important;
    box-sizing: border-box !important;
    min-height: var(--uc-newtab-row-height) !important;
    margin: 0 !important;
    padding: 0 var(--tab-block-margin, 2px) !important;

    background: transparent !important;
    box-shadow: none !important;
  }

  @media -moz-pref("zen.view.show-newtab-button-top") {
    #tabbrowser-arrowscrollbox-periphery {
      order: -999 !important;
      top: var(--uc-newtab-edge-nudge) !important;
      bottom: auto !important;
    }
  }

  #tabbrowser-arrowscrollbox-periphery > #tabs-newtab-button {
    position: relative !important;
    z-index: 1 !important;
    isolation: isolate !important;
    overflow: hidden !important;
    appearance: none !important;
    -moz-appearance: none !important;
    box-sizing: border-box !important;
    align-items: center !important;
    width: 100% !important;
    min-height: var(--uc-newtab-height) !important;
    margin: 0 !important;
    padding-inline: var(--tab-inline-padding, 10px) !important;
    border-radius: var(--border-radius-medium, 8px) !important;
    color: inherit !important;
    opacity: 1 !important;
    background-color: var(--uc-newtab-button-bg) !important;
    background-image: none !important;
    background-clip: border-box !important;
    box-shadow: inset 0 0 0 9999px var(--uc-newtab-button-bg) !important;
  }

  #tabbrowser-arrowscrollbox-periphery > #tabs-newtab-button:hover {
    background-color: var(--uc-newtab-button-bg-hover) !important;
    background-image: none !important;
    box-shadow: inset 0 0 0 9999px var(--uc-newtab-button-bg-hover) !important;
  }

  #tabbrowser-arrowscrollbox-periphery > #tabs-newtab-button .toolbarbutton-text {
    position: relative !important;
    z-index: 1 !important;
    display: flex !important;
    align-items: center !important;
  }

  #tabbrowser-arrowscrollbox-periphery > #tabs-newtab-button .toolbarbutton-icon {
    position: relative !important;
    z-index: 1 !important;
    background: transparent !important;
  }
}
```

**Note:** I don't think AI code is a proper solution but, since I can't code myself, it was the only way I could get it fixed for myself and I am sharing this hoping it can help those who are struggling to find a decent workaround since there isn't any (at least I couldn't find one) and can't stand that button scrolling with tabs as match as I do. 
#### Cheers
