### DISCUSSION TITLE
Bookmarks Menu above new tab button (or separate containers for essentials/tab list/workspaces)

### DISCUSSION THREAD

**Discussion by Simbians** [zen-browser/desktop#8468] [Ideas]
Hey All,

The specific feature I am aiming for is to have the bookmarks menu button sit above the "New Tab" button but below the Essentials box. I've tried to make this work by creating a zen mod but have hit a wall in my ability as the essentials box and the tabs list are within the same container in the side bar and the bookmarks menu, when enabled, sits outside of this container, on the same level in the hierarchy.

Hence I cannot place the bookmarks menu in what I consider a sensible location within the toolbar using the customise toolbar or Zen Mods through CSS.

If the layout was changed to have the tabs, workspaces and essentials sit within their own containers then these could be moved about through either the Customise Toolbar function or through Zen Mods using CSS (as with the bottom essentials mod, which works because the essentials are in the same container as the tab list).

Here's my sidebar right now and a mock-up of how it could look:

![image](https://github.com/user-attachments/assets/fe7960d6-9089-49e1-a39a-a910bf664aae)

**Comment by ClixTW** [comment]
Hi! How did you position the bookmarks menu like in the example on the left side of the image?

I'm trying something similar — in order to make room for the button placement, I had to move the bottom of the sidebar to the top.
But doing it this way comes with some trade-offs, and it doesn't feel very elegant.

![未命名](https://github.com/user-attachments/assets/21bd3618-cddb-4553-8e06-77c3849d07f6)

Here’s my CSS:

```css
/* ========================================================================== */

/* Reorder and customize layout of bottom buttons */
#zen-sidebar-bottom-buttons {
  display: flex !important;
  flex-wrap: wrap !important;
  row-gap: 0 !important;
  margin-top: -4px !important;
  margin-bottom: 4px !important;
  order: 0 !important;
}

/* Reorder toolbar items */
.toolbar-items {
  order: 1 !important;
}

/* Reorder media tool */
#zen-media-controls-toolbar {
  margin-bottom: 4px !important;  
  order: 2 !important;
}

/* Center bookmarks bar */
#PlacesToolbarItems {
  justify-content: center !important;
}


/* ========================================================================== */

/* Reorder the workspace tabs section */
.zen-workspace-tabs-section.zen-current-workspace-indicator {
  order: 1 !important;
}

/* Hide indicator by default unless hovered */
:root:has(.zen-current-workspace-indicator:not(:hover)) {
  .zen-current-workspace-indicator {
    opacity: 0 !important;
    transition: opacity 0.2s ease-out;
  }

  .zen-current-workspace-indicator:hover {
    opacity: 1 !important;
    transition: opacity 0.2s ease-in;
  }
}


/* ========================================================================== */

/* Hide the workspace indicator icon */
.zen-current-workspace-indicator-icon {
  display: none !important;
}

/* Container for workspace icon */
.zen-workspace-icon {
  position: relative;
  color: transparent;
}

/* Add a centered white dot as a custom indicator */
.zen-workspace-icon::before {
  position: absolute;
  content: '';
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  inline-size: 5px; /* Change this to adjust dot size */
  aspect-ratio: 1;
  background-color: white;
  border-radius: 50%;
}
```

If you don’t mind, I’d really appreciate it if you could share your current CSS too 🙏
