### DISCUSSION TITLE
Update check improvements

### DISCUSSION THREAD

**Discussion by astatine** [zen-browser/desktop#896] [Ideas]
Hello! I would like Zen to:

1. Not automatically check for updates (or prompt the user) for the rest of the day if I have dismissed an update alert
2. Provide an option in Settings to completely disable automatic update checks forever or for a configurable amount of time (6 hours, 1 day, 1 week, etc.)

Note that I'm not discouraging updates, just aggressive automatic update checks and user prompts. Thanks!

**Comment by trespaul** [comment]
This is also annoying for people who use package repositories. If an update is available but not yet packaged, the end-user can't do anything about it except dismiss the dialog over and over again until the new version is packaged.

**Comment by joinemm** [comment]
Using NixOS with zen from a flake and this is really annoying, having to dismiss the update every time I start the browser. Please add an option to disable the update check. I want to manage updates with my package manager like every other linux application.

**Reply by trespaul** [reply]
This is exactly my context as well! :) I assume everyone on NixOS is using https://github.com/MarceColl/zen-browser-flake while waiting for the nixpkgs package.

**Reply by Grantimatter** [reply]
> Using NixOS with zen from a flake and this is really annoying, having to dismiss the update every time I start the browser. Please add an option to disable the update check. I want to manage updates with my package manager like every other linux application.

In the same boat here.
I've updated some settings in `about:config` that seem to be working to stop the update prompt from popping up.

Here's what I changed, not sure if every change is needed since I tried them all at once.
Navigate to the `about:config` url and update these values:
```toml
app.update.auto = false
app.update.checkInstallTime = false
app.update.promptWaitTime = -1
app.update.silent = true    # May need to create this one, just select Boolean at the bottom of the page after typing it in.
```

If this works to keep the notification from showing, I'll also want to add it to my nix flake somehow. I haven't messed with Firefox / zen configs there before.
