### ISSUE TITLE
Rounded corners broken with Zen Dream and Zen Galaxy

### ISSUE THREAD

**Issue by kittybwained** [zen-browser/desktop#1508]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The latest update broke the rounded corners on the Zen Dream and Zen Galaxy themes. The square webpages now render on top of the rounded corners.
![image](https://github.com/user-attachments/assets/eb9eca4a-945f-4cc2-9d08-1b0c8be4adf1)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1

### What platform are you seeing the problem on?

Windows

**Comment by kittybwained** [comment]
Found a workaround, add:
```css
browser {
	border-radius: var(--zen-webview-border-radius, var(--zen-border-radius)) !important;
}
```
to your userChrome.css file.
