### ISSUE TITLE
Font size on tabs too small

### ISSUE THREAD

**Issue by coderstarrer** [zen-browser/desktop#1524]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Screenshot 2024-09-18 130204](https://github.com/user-attachments/assets/adae3888-6e15-4b29-a6ed-dcce70c952d7)
The font size is too small to read 
This is different to all the other font-size issues because the previous issues were mostly about the +new tab button but now its all tabs

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2(64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by kittybwained** [comment]
Getting this too, it's very annoying. How the hell do you manage to ship an update that's clearly this broken?

**Comment by kittybwained** [comment]
Found a workaround, add:
```css
.tab-text {
	font-size: 12px !important;
}
```
to your userChrome.css file.

**Comment by coderstarrer** [comment]
And you could also put
```
 #vertical-tabs-newtab-button {
	font-size: 12px !important;
}
```
to the userChrome.css

**Comment by 500mhzz** [comment]
> Found a workaround, add:
> 
> ```css
> .tab-text {
> 	font-size: 12px !important;
> }
> ```
> 
> to your userChrome.css file.

To do this in Zen, go to the three dots beside the minimize button, click help, than `More Troubleshooting Information`, scroll down till you see Profile Folder with the `Open Folder` button beside it. Click it and than go to `chrome > zen-themes` than find or create any theme in there.

**Comment by kittybwained** [comment]
Also recommend adding:
```css
.tab-icon-sound-label.tab-icon-sound-playing-label {
  font-size: 9px !important;
}
```

**Comment by User344** [comment]
Two updates that break something so basic back-to-back is insane

**Comment by jurienhamaker** [comment]
Stop whining guys. Its almost a solo dev doing shit to make your lifes better. If you got something to complain besides reporting an issue or a solution, start contributing. 

@User344 @kittybwained

**Comment by PierreL-H** [comment]
I believe this should be fixed in the next release so I'm a little late, but in the meanwhile this is what I have
```css
  /* tab list font size fix */
  #tabbrowser-tabs[orient="vertical"] {
    & #newtab-button-container {
      font-size: unset !important;
    }
  }
  
  #tabbrowser-tabs {
    & .tabbrowser-tab {
      font-size: unset !important;
    }
  }
```

This was fixed here for the tab text: https://github.com/zen-browser/desktop/commit/4d4c2fd6768080881df4f3e887907d590ea87694#diff-1e316fee8b8eb75a4ffdc132e053a036cc22062da466549a3326fdbbdbb5b9c9L73 
I couldn't find where the rule for `#newtab-button-container` was though.
