### ISSUE TITLE
Reaching tabs overflow removes a bottom webview gap

### ISSUE THREAD

**Issue by thunder-al** [zen-browser/desktop#2162]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Windows 11, Zen 1.0.1-a.9 (64-bit) (bug persists at least with 3 last versions and maybe in any other platform)

Filling tabs column with more than available height causes overflow and scroll bar to appear (as expected) and removes bottom gap between website area and the bottom of the window (unexpected). (look closely to the bottom part of the window in the video)

Tested with/without:
* normal (as in the video) and "icons only" (slim) tabs
* maximized (aka fullscreen, as in the video) and normal window size
* with and without "Remove Browser Padding (v1.0.2)" zen theme (with this theme this bug still persists and cause small part of the web view at the bottom)

https://github.com/user-attachments/assets/4e30b42b-71ea-41e4-bcea-7c36b076e961

Suggestion:
Wrap tabs which container which will not cause layout shift on overflow-y.  
(Probably will make a merge request with changes like that later)
```html
<div class="tabs-container">
    <div class="tabs-list">
        <div class="tab"></div>
        <div class="tab"></div>
        <div class="tab"></div>
        <div class="tab"></div>
    </div>
</div>
```
```css
.tabs-container {
    position: relative;

    /* allow tabs to scroll on overflow */
    overflow-x: hidden;
    overflow-y: auto;

    /* make wrapper fill available height */
    /* if left panel's elements wrapped flex column */
    flex-grow: 1;
    /* or */
    height: 100%;
}

.tabs-list {
    /* make tabs list absolute */
    /* it will prevent layout shift on overflow */
    /* and keep scroll from .tabs-container */
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
}

.tab {
    /* singular website tab */
}
```

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Windows
