### ISSUE TITLE
Inconsistent resize cursors in split view resize mode

### ISSUE THREAD

**Issue by Jai-JAP** [zen-browser/desktop#2252]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The cursors in split view rearrange mode are inconsistent when resizing vertical vs horizontal view.

![Horizontal resize](https://github.com/user-attachments/assets/5d74ae62-ec8b-4fbd-baaf-0e943ffdd600)
![Vertical resize](https://github.com/user-attachments/assets/3301b64d-774c-453a-b27a-5e36091e847a)

Note that the cursor used in vertical resize is a proper resize cursor with 2 arrow heads, whereas the one in horizontal resize is a window resize cursor (specifically resize from bottom one).

This is an inconsistency and a visual bug while resizing horizontally.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux

**Comment by Jai-JAP** [comment]
This can be solved by changing the following lines 

https://github.com/zen-browser/desktop/blob/065e82534e1cf2acf2f29161c864838f0e24f57f/src/browser/base/content/zen-styles/zen-decks.css#L100-L117

to 

```css
.zen-split-view-splitter {
  visibility: inherit;
  -moz-subtree-hidden-only-visually: 0;
  position: absolute;
  pointer-events: all;
}


.zen-split-view-splitter[orient='vertical'] {
  width: var(--zen-split-row-gap);
  margin-left: calc(var(--zen-split-row-gap) / -2);
  cursor: ew-resize;

}


.zen-split-view-splitter[orient='horizontal'] {
  height: var(--zen-split-column-gap);
  margin-top: calc(var(--zen-split-column-gap) / -2);
  cursor: ns-resize;
}
```
