### ISSUE TITLE
Fullscreen video doesnt fit inside window when disabling padding

### ISSUE THREAD

**Issue by danielsvane** [zen-browser/desktop#2334]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There is a weird interaction of settings I'm using.

In `about:config` I have `full-screen-api.ignore-widgets` set to true, to allow for fullscreen videos to only take up the size of the window theyre in.

I'm using hyprland window manager.

I'm running in compact mode in the browser. I have further installed Zen Paper Cut theme, to remove the last padding from the browser window.

When fullscreening a youtube video, the video will use my monitors size, not the windows size, but be masked by the window. A resize of the window will make the video fit inside the window again:

![image](https://github.com/user-attachments/assets/07351803-4bfc-4df4-ab86-e1ca3040acdc)

This only happens when I use the Paper Cut theme, or set the relevant css rules manually:

```css
#tabbrowser-tabbox, #tabbrowser-tabpanels {
  padding: 0px !important;
  margin: 0px !important;
}
```

When I still have the default padding, the fullscreen works as expected.

![image](https://github.com/user-attachments/assets/f6faf4e2-b7a9-4028-ac9b-0d8c23fb9278)

I know the solution is simple, just dont remove the extra padding in the browser window. I just wanted to check if there was a solution, where fullscreen works normally, and I can remove the padding at the same time.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Linux

**Comment by danielsvane** [comment]
I managed to "fix" this, by using the following css:

```css
#tabbrowser-tabpanels,
#tabbrowser-tabbox {
    padding: 0 !important;
}

:root[inDOMFullscreen="true"] #appcontent,
:root[inDOMFullscreen="true"] #tabbrowser-tabpanels {
    margin: -1px;
}
```

I will of course miss 1 pixel around the fullscreen content, but it works in lack of better options. Apparently, some form of size difference in the window between fullscreen and non-fullscreen is required for the video to scale down properly.
