### ISSUE TITLE
Scroll bars cannot be hidden using CSS

### ISSUE THREAD

**Issue by Tygo-van-den-Hurk** [zen-browser/desktop#2338]
### Captchas

- [X] I have searched existing issues and avoided creating duplicates.
- [X] I have read the instructions.
- [X] I am not filing an enhancement request.

### What happened?

The following CSS code is intended to hide scrollbars across all major browsers:

```css
* {
    overflow: -moz-scrollbars-none;
    -ms-overflow-style: none;
    scrollbar-width: none;
} 
*::-webkit-scrollbar { 
    display: none; 
}
```

While this implementation successfully hides scrollbars in all major browsers, it appears that the Zen Browser doesn't follow this trend.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

#### Steps to Reproduce:

- Apply the provided CSS code in any project.
- Open the project in Zen Browser.
- Observe that the scrollbars remain visible.

### Version

1.0.1-a.6 (64 bit)

### What platform are you seeing the problem on?

Linux
