### ISSUE TITLE
[Twilight] Top Margin Missing in Browser

### ISSUE THREAD

**Issue by amtoaer** [zen-browser/desktop#3207]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Top margin is missing regardless of whether compact mode is enabled or not.

![图片](https://github.com/user-attachments/assets/72dcbecd-46a7-4346-aed4-df61d2cdd034)

![图片](https://github.com/user-attachments/assets/b8021f52-13b1-44ff-ad05-c5bfba037850)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.20(Firefox 132.0.2)(2024-11-26)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by 12th-devs** [comment]
Sorry I don't have a solution. But can you please give me your theme setup it's beautiful 😍

**Comment by amtoaer** [comment]
@Anoms12 Sure, this is the default layout of Zen Twilight. I only made a small change by customizing the theme color.

![图片](https://github.com/user-attachments/assets/efb87f3b-b150-4824-b1b1-74dbc0c0dc7e)

**Comment by 12th-devs** [comment]
Thanks 😍

**Comment by pipashu** [comment]
> 当然，这是 Zen Twilight 的默认布局。我只通过自定义主题颜色进行了很小的更改。
> 
> ![图片](https://private-user-images.githubusercontent.com/32017007/390331734-efb87f3b-b150-4824-b1b1-74dbc0c0dc7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzMxOTYsIm5iZiI6MTczMjc3Mjg5NiwicGF0aCI6Ii8zMjAxNzAwNy8zOTAzMzE3MzQtZWZiODdmM2ItYjE1MC00ODI0LWIxYjEtNzRkYmMwYzBkYzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1NDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYTM3Y2Q4YTBmZTQyYjBiZGM0YTVhMmQwMWY0MGI4ZDQ5ODNhMTI3OGJiNDlhNzQ4ZWM2OWY0NTM1NmQxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NHPg2YScT3vGvu1PWSVZYfOg0YHpBSFtI5Lhnpj7ZmU)

这个面板是怎么调出来的？

**Comment by jannisborgers** [comment]
I did a quick dive because I want no margins (see below), and found a possible solution for the top margin. 

## Step 1: Add userChrome.css by following this guide:
https://docs.zen-browser.app/guides/live-editing

## Step 2: Add back top margin
Adding this gets the top margin back. 

> [!NOTE]  
> I’m not sure if this is a bug or related to coming changes (horizontal tabs?), because it looks very much like it is intended. So use with caution.

```css
/* userChrome.css */
:root:not([inDOMFullscreen='true']):not([chromehidden~='location']):not([chromehidden~='toolbar']) {
  & #zen-tabbox-wrapper {
    margin-top: var(--zen-element-separation) !important;
  }
}
```

## Alternative: No margins
Removing the margins from all sides is a nice alternative if you prefer to not have a frame anywhere but the tab bar. 

> [!NOTE]  
> Without any chrome, there is no way to drag the window with the mouse. I don’t do this as I use Moom to move windows, but keep it in mind!

```css
/* userChrome.css */
/* Remove all margins around viewport */
:root:not([inDOMFullscreen='true']):not([chromehidden~='location']):not([chromehidden~='toolbar']) {
  & #zen-tabbox-wrapper {
    margin: 0 !important;
}

/* Remove left window margin in compact mode (brute) */
@media (-moz-bool-pref: 'zen.view.compact') {
    @media (-moz-bool-pref: 'zen.view.compact.hide-tabbar') {
      #zen-appcontent-wrapper {
        margin-left: 0 !important;
    }
  }
}
```

I have only tested this with my configuration, but maybe it will help those waiting for a bugfix (if it’s a bug).

**Comment by jannisborgers** [comment]
With the latest Twilight release, the above is not needed as the top margin is back. If you want no margins, the userChrome.css has to change, though:

```css
/* Remove all margins around viewport (only works for right and bottom) */
:root:not([inDOMFullscreen='true']):not([chromehidden~='location']):not([chromehidden~='toolbar']) {
  & #zen-tabbox-wrapper {
    margin: 0 !important;
  }
}

/* Remove top window margin */
:root[zen-single-toolbar="true"]:not([customizing]) {
  & #zen-appcontent-navbar-container {
    min-height: 0 !important;
    height: 0 !important;
  }
}

/* Remove left window margin in compact mode */
@media (-moz-bool-pref: 'zen.view.compact') {
  @media (-moz-bool-pref: 'zen.view.compact.hide-tabbar') {
    #zen-appcontent-wrapper {
      margin-left: 0 !important;
    }
  }
}
```
