### ISSUE TITLE
Overflow indicators in the tab bar have become aggressive

### ISSUE THREAD

**Issue by different55** [zen-browser/desktop#3230]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

As of the latest update, Zen has picked up some overflow indicators in the tab bar that are a bit visually jarring.

<img width="449" alt="Screenshot 2024-11-27 at 7 27 04 PM" src="https://github.com/user-attachments/assets/33dd26e5-e22a-450f-861c-9ef06471bc8f">

Cracking open the browser inspector, these indicators are these two elements:

```xml
<spacer part="overflow-start-indicator"/>
<spacer part="overflow-end-indicator"/>
```

Who are picking up their new color from this bit of CSS:

```css
#tabbrowser-arrowscrollbox {
  &[orient="vertical"] {
    &::part(overflow-start-indicator), &::part(overflow-end-indicator) {
      background-image: linear-gradient( to top, transparent 0%, var(--toolbar-bgcolor));
    }
  }
}
```

At least on my machine, --toolbar-bgcolor is set to a nearly-white color that doesn't fit in with any theme I've tried throwing at it.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

macOS - Intel

**Comment by different55** [comment]
This issue was caused by a.20, reverted in a.21, and fixed later.

1. dosu I hate you
2. this issue can be closed

**Comment by different55** [comment]
dosu do not talk to me

does github have a block feature for bots I will find it

**Comment by different55** [comment]
dosu I am at my freaking limit do nOT test me

**Comment by different55** [comment]
```css
.js-timeline-item:has(.js-comment-container .author[href="/apps/dosubot"]), .Details-element .js-timeline-item:has(.js-comment-container .author[href="/apps/dosubot"]) {
  display: none;
}
```
