### ISSUE TITLE
Accented links & colors are impossible to read in settings

### ISSUE THREAD

**Issue by VoxelPrismatic** [zen-browser/desktop#3727]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

That help link is actually impossible to see.
![image](https://github.com/user-attachments/assets/7a848bea-2da5-4438-8ee4-b78d31732a19)

Direct comparison:
<table>
  <tr>
    <th>Zen</th>
    <th>Firefox</th>
  </tr>
  <tr>
    <td>

![image](https://github.com/user-attachments/assets/f9b45ff2-1292-4d09-8007-f25565793423)

</td>
<td>  

![image](https://github.com/user-attachments/assets/6b9c0e0a-ae56-4755-a807-5747cf7bdf95)

</td>
  </tr> 
  <tr>
    <td>

![image](https://github.com/user-attachments/assets/de799628-ed41-4c0b-9fe9-b2d01dbd6904)

</td>
<td>

![image](https://github.com/user-attachments/assets/c4898a7a-85ea-4f99-af0b-547d00eeefc2)

</td>
</table>
  

# Possibly relevant CSS
In `zen-theme.css`
```css
:host(:is(.anonymous-content-host, notification-message)), :root, .zenLooksAndFeelColorOption {
  /* ... */
  --button-primary-bgcolor: var(--in-content-primary-button-background) !important;
  --button-primary-hover-bgcolor: var(--in-content-primary-button-background-hover) !important;
  --button-primary-active-bgcolor: var(--in-content-primary-button-background-active) !important;

  /* ... */
  --color-accent-primary: var(--button-primary-bgcolor) !important;
  --color-accent-primary-hover: var(--button-primary-hover-bgcolor) !important;
  --color-accent-primary-active: var(--button-primary-active-bgcolor) !important;

  /* ... */
  --in-content-primary-button-background: color-mix(in srgb, var(--zen-primary-color) 10%, var(--zen-branding-bg) 90%) !important;
  --in-content-primary-button-background-hover: color-mix(in srgb, var(--zen-primary-color) 15%, var(--zen-branding-bg) 85%) !important;
  --in-content-primary-button-background-active: color-mix(in srgb, var(--zen-primary-color) 20%, var(--zen-branding-bg) 80%) !important;
}
```

### Solution?

This `color-mix(in srgb, var(--zen-primary-color) 10%, var(--zen-branding-bg) 90%)` is the issue. Perhaps try mixing the opposite branding background and playing with the mix% to produce the following result:
```css
/* zen-theme.css */
:host(:is(.anonymous-content-host, notification-message)), :root, .zenLooksAndFeelColorOption {
  /* ... */
  --in-content-primary-button-background: color-mix(in srgb, var(--zen-primary-color) 80%, var(--zen-branding-bg-reverse) 20%) !important;
  --in-content-primary-button-background-hover: color-mix(in srgb, var(--zen-primary-color) 85%, var(--zen-branding-bg-reverse) 15%) !important;
  --in-content-primary-button-background-active: color-mix(in srgb, var(--zen-primary-color) 30%, var(--zen-branding-bg-reverse) 70%) !important;
}
```

https://github.com/user-attachments/assets/c8bc72ba-82f7-47a3-b936-f0605b4f8061

Not perfect, but significantly better.

### Software details
- Linux
  - Ubuntu 24.04 (KDE Neon)
  - Occurs under both X11 and Wayland
- Zen
  - v1.0.2-b.1 (Firefox 133.0) [x64]
  - Installed via Flatpak

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Linux
