### ISSUE TITLE
Bookmarks Toolbar automatically hides in "Single toolbar" layout even though "Alway Show" is enabled

### ISSUE THREAD

**Issue by mheidinger** [zen-browser/desktop#4591]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

1. Create a new profile for a clean repro setup
2. Select "Single toolbar" as layout
3. Create a bookmark in the bookmarks toolbar
4. Select bookmarks toolbar to "Always show"

After these steps the toolbar is still automatically hidden, making it hard to get to as the hover hitbox is quite small.
Expectation is that the setting "Always show" is honored and the toolbar is always visible.

The expected behaviour can be achieved with the following `userChrome.css`:
```css
#zen-appcontent-navbar-container {
  height: var(--zen-toolbar-height) !important;
  opacity: 1 !important;
}

#PersonalToolbar {
  opacity: 1 !important;
}%
```

Screen Recording:
https://github.com/user-attachments/assets/3cd0ddda-7bde-41f9-a53b-2860c2e05c36

If someone has a few hints as to where to start fixing the issue, I am also happy to contribute myself :)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.2b

### What platform are you seeing the problem on?

macOS - aarch64
