### ISSUE TITLE
Menu Alignment Issues

### ISSUE THREAD

**Issue by sillvva** [zen-browser/desktop#4691]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

There are several menus that appear to have alignment issues on both Windows and MacOS.

## Windows
![Image](https://github.com/user-attachments/assets/c2510416-afc5-4856-93c5-8a80f48980e3)

## MacOS
![Image](https://github.com/user-attachments/assets/a9d7984b-b743-4a29-b069-80884c8d1597)
![Image](https://github.com/user-attachments/assets/aaf325a4-d9b7-46b7-9fdf-f57a608316a0)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.2b

### What platform are you seeing the problem on?

Other

### Relevant log output if applicable

```shell

```

**Comment by sillvva** [comment]
It seems the issue has to do with menu items that count as checkboxes. This sort of fixes it:

```css
:not(:not(menubar) > menu, #ContentSelectDropdown) > menupopup > menuitem:not(.menuitem-iconic, [type="checkbox"], [type="radio"], .in-menulist, .in-menulist menuitem, .unified-nav-current), :not(:not(menubar) > menu, #ContentSelectDropdown) > menupopup > menu:not(.menu-iconic, [type="checkbox"], [type="radio"], .in-menulist, .in-menulist menu, .unified-nav-current), #toggle_toolbar-menubar, #PanelUI-history toolbarbutton, #unified-extensions-context-menu menuitem {
  padding-inline-start: calc( var(--fp-contextmenu-menuitem-padding-inline) + 16px + var(--fp-contextmenu-menuicon-margin-inline) ) !important;
  &[type="checkbox"] {
    padding-inline-start: 34px !important;
    .menu-iconic-text {
      padding-inline-start: 1px !important;
    }
    &[checked="true"] {
      padding-inline-start: 8px !important;
      --menu-image: none !important;
      .menu-iconic-text {
        padding-inline-start: 26px !important;
      }
    }
  }
}
```

### Before
![Image](https://github.com/user-attachments/assets/1fa97053-b6c8-4389-9971-a439d1eece6c)

### After
#### Pin to Toolbar is checked
![Image](https://github.com/user-attachments/assets/d1784556-41a6-4fc3-a5ff-0bf174e8c69a)

#### Pin to Toolbar is unchecked
![Image](https://github.com/user-attachments/assets/8cfd1d90-2e12-4b99-9ce7-3cb8de2ee670)
