### ISSUE TITLE
Pinned tabs not staying on top

### ISSUE THREAD

**Issue by BookCatKid** [zen-browser/desktop#5015]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Pinned tabs used to always stay on top, but now (after the change that flipped the tabs up-side down so to speak) When I scroll down the pinned tab also scrolls.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.4b

### What platform are you seeing the problem on?

Windows

### Relevant log output if applicable

```shell

```

**Comment by thecaralice** [comment]
@mauro-balades are you sure it is completed? I do not see any resolution.

**Comment by poulpor** [comment]
Errr, what's the use of a "pinned" tab if it disappears when I scroll down tabs ???
Is it because of the drag and drop feature to add tabs to the pinned part, was it the only solution ?

**Comment by thecaralice** [comment]
This is still an issue on 1.8.2b. @mauro-balades please reopen.

**Comment by silverling** [comment]
Found workaround solution from discord:

Add this snippet into your `userChrome.css`, tested on version 1.10.3b

```css
/* pinned tabs stay pinned in space not scrolling*/
@media (-moz-bool-pref: "zen.tabs.vertical") {
  
  #zen-browser-tabs-container {
    position: absolute;
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    overflow-y: clip;
  }

  #vertical-pinned-tabs-container .zen-workspace-tabs-section {
    overflow: auto;
    position: sticky !important;
  }
  
  #tabbrowser-arrowscrollbox {
    min-height: 0 !important;
    max-height: 100% !important;
    position: relative;
  }
  #tabbrowser-arrowscrollbox .zen-workspace-tabs-section {
    position: relative !important;
    overflow-y: auto;
    margin-top: initial !important;
  }
  
}
```

Credit: https://discord.com/channels/1088172780480114748/1281374861536526356/1346212399258009712

**Comment by silverling** [comment]
> Found workaround solution from discord:
> 
> Add this snippet into your `userChrome.css`, tested on version 1.10.3b
> 
> /* pinned tabs stay pinned in space not scrolling*/
> @media (-moz-bool-pref: "zen.tabs.vertical") {
>   
>   #zen-browser-tabs-container {
>     position: absolute;
>     width: 100%;
>     height: 100%;
>     display: flex;
>     flex-direction: column;
>     overflow-y: clip;
>   }
> 
>   #vertical-pinned-tabs-container .zen-workspace-tabs-section {
>     overflow: auto;
>     position: sticky !important;
>   }
>   
>   #tabbrowser-arrowscrollbox {
>     min-height: 0 !important;
>     max-height: 100% !important;
>     position: relative;
>   }
>   #tabbrowser-arrowscrollbox .zen-workspace-tabs-section {
>     position: relative !important;
>     overflow-y: auto;
>     margin-top: initial !important;
>   }
>   
> }
> 
> Credit: https://discord.com/channels/1088172780480114748/1281374861536526356/1346212399258009712

This messed up the workspace switch functionality, sadly. Need to find other solutions.

**Comment by Cybolic** [comment]
Can this get re-opened? It's very much still an issue.
In the latest version (1.12.8b), the following `userChrome.css` can be used to work around the issue, but it's getting really tiresome to have to re-implement this every few versions.

```css
@media (-moz-bool-pref: "zen.tabs.vertical") {
  
  zen-workspace > arrowscrollbox.workspace-arrowscrollbox {
    overflow-y: hidden !important;
    flex-basis: 100%;
  }
  #tabbrowser-arrowscrollbox .zen-workspace-pinned-tabs-section {
    flex: 1 1 0;
  }
  #tabbrowser-arrowscrollbox .zen-workspace-normal-tabs-section {
    flex: 1 1 0;
    overflow-y: auto !important;
  }

}
```
