### ISSUE TITLE
Custom background for New tab

### ISSUE THREAD

**Issue by spectrum705** [zen-browser/desktop#547]
### What feature would you like to see?

Hi,
requesting a small feature to be able to add custom bg for new tab page. Selecting random images from a specified folder /(or maybe a cloud storage folder?)
Thank you

### What platform are you seeing the problem on?

Windows

**Comment by poopsicles** [comment]
perhaps you could use the [Tabliss](https://addons.mozilla.org/en-US/firefox/addon/tabliss/) extension?

**Comment by tunalad** [comment]
That can be done via `userContent.css`
```css
@-moz-document url-prefix(about:home), url-prefix(about:newtab) {
    body {
        background: url(path/to/image) !important ;
        background-size: cover !important ;
    }
}
```
But I definitely agree that there should be an option to user our own images next to the built-in ones
