### ISSUE TITLE
Keyboard-only side / top bar toggle

### ISSUE THREAD

**Issue by kLabz** [zen-browser/desktop#548]
### What feature would you like to see?

In compact mode, allow user to disable mouse hover toggling of top/side bars (can use current keyboard shortcuts for toggling it)

### What platform are you seeing the problem on?

Linux

**Comment by kLabz** [comment]
Current workaround, in `userChrome.css`:

```css
@media (-moz-bool-pref: "zen.view.compact") {
  #zen-appcontent-navbar-container:not([zen-user-show]) toolbar,
  #navigator-toolbox:not([zen-user-show]) #titlebar {
    display: none;
  }
}
```
