### ISSUE TITLE
Compact mode makes website's side contents unreachable

### ISSUE THREAD

**Issue by MG-LSJ** [zen-browser/desktop#549]
### What happened?

Compact mode triggers the sidebar to overlay over website content. But the trigger zone is so big that it covers the screen when trying to use a website's sidebar or any content on the sides.

If there is a fix, I was not able to find one. The sidebar trigger zone should be moved to the extreme corner

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by kLabz** [comment]
As a workaround, adding styles for `#navigator-toolbox:not([zen-user-show]):not(:hover) #titlebar` in your `userChrome.css` should help you change its trigger zone.

For example:

```css
@media (-moz-bool-pref: "zen.view.compact") {
  #navigator-toolbox:not([zen-user-show]):not(:hover) #titlebar {
    min-width: 4px !important;
  }
}
```
