### ISSUE TITLE
chore(visual): favicon shifting when audio playing on small icon view

### ISSUE THREAD

**Issue by qtchaos** [zen-browser/desktop#608]
### What happened?

When having the sidebar in the small view (so that only the favicon is visible) and there is a tab playing audio, switching to it shifts the favicon to the left (by a few pixels) to create space for the mute button.

I'm assuming that this is not wanted behavior since the shift is so small that it doesn't actually make muting easier.

![zen_example](https://github.com/user-attachments/assets/3742bed0-c627-4f98-9772-63f4321f54c4)

Found the css in question which applies the margin but can't find it in this repo?

`📁tabs.css:247`
```css
/* Width/height & margins apply on tab icon stack children */
.tab-throbber,
.tab-icon-pending,
.tab-icon-image,
.tab-sharing-icon-overlay,
.tab-icon-overlay {
  height: 16px;
  width: 16px;

  &:not([pinned]) {
    margin-inline-end: 5.5px; <-- issue stems from this
  }
}
```

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Windows
