### ISSUE TITLE
Now playing audio icon hiding favicon

### ISSUE THREAD

**Issue by lolouthefox** [zen-browser/desktop#685]
### What happened?

![image](https://github.com/user-attachments/assets/1b798a0e-e45f-448d-ae36-49ab6bea9850)
The now playing audio icon (and button) is hiding favicon.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by DaitiDay** [comment]
+1

**Comment by ch4og** [comment]
Check these theme made for hiding tab mute
https://www.zen-browser.app/themes/053a3ffa-9233-4554-88f3-076e6a6ebb43

**Comment by DaitiDay** [comment]
I managed to fix the "visibility issue" using the following CSS in `userChrome.css`:
```css
.tab-icon-overlay {
  -moz-box-ordinal-group: 0 !important;
  border-radius: 50% !important;
  margin: initial !important;
  visibility: visible !important;
  margin-right: 0px !important;
  opacity: 1 !important;
  transform: translate(60%, -35%) scale(0.9) !important;
  color: #000000 !important;
  background-color: #ffffff !important;
}

.tab-icon-overlay:hover {
  color: #000000 !important;
  background-color: #ffffff !important;
}

.tab-icon-overlay:not(:focus) {
    visibility: visible !important;
    opacity: 1 !important;
}
```
Unfortunately, I can't get the icon to display when the tab is not focused, even with the last four lines in userChrome.css. Can someone help me troubleshoot or fix this?

Another question: If I wanted to add this CSS snippet to the theme store for everyone to use, how can I achieve that? Is there a guide on how to submit such a snippet that isn't a "standard" theme?
