### ISSUE TITLE
Scroll bar can't be scrolled from the right edge of the window (Windows)

### ISSUE THREAD

**Issue by perigozin** [zen-browser/desktop#6979]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue cannot be reproduced once I removed all my Mods and Custom CSS.

### What happened?

As with any browser or program it is expected to be able to just move the mouse to the edge of the screen and clicking the scrollbar to be able to quickly scroll.
In Zen (at least on Windows) there is a small gap between the scrollbar and the edge of the browser window, so whenever I need to use the scrollbar I have to actually look at it and click exactly on it, instead of just moving the cursor to the extreme right, knowing the scrollbar will automatically be in focus, which is annoying (I mostly use the scroll wheel but sometimes for scrolling longer pages the scrollbar is still useful).

I'm not even saying the gap should be removed, I like the design choice, but maybe the window border on the right side should register clicks for the scrollbar. Just a small UX improvement that would improve navigation. 

![Image](https://github.com/user-attachments/assets/c6799aab-b0a7-4e29-bd10-3220d8583661)

### Version

**1.9.1b** and **1.91.t**

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Other

**Comment by sporocyst** [comment]
The gap belongs to the browser frame, while the scrollbar belongs to webpage itselft. It doesn't make sence that you can change the content of webpage when you are hovering over outside of webpage. But you can sacrifice right border via CSS to reduce the inconvenience

**Comment by perigozin** [comment]
> The gap belongs to the browser frame, while the scrollbar belongs to webpage itselft. It doesn't make sence that you can change the content of webpage when you are hovering over outside of webpage. But you can sacrifice right border via CSS to reduce the inconvenience

It makes even less sense having a behavior that differs from any other software. Muscle memory is a thing and this is obviously an UX issue.

**Comment by Propheticus** [comment]
I can see how this is a UX issue for those that scroll by throwing the mouse far right and clicking.

As a workaround you can remove the 8px gaps by going into advanced preferences `about:config` and setting `zen.theme.content-element-separation` to 0


<details><summary>If it breaks it breaks, use at your own risk: CSS to only remove borders when window is maximised. </summary>

This goes into `userChrome.css` within the profile's `chrome` folder:
```CSS
/* Remove padding around the window, but only when it is maximised */
:root[sizemode="maximized"] {
	--zen-element-separation: 0.1px !important;
}
/* Restore the split tabs draggable separator thickness */
#tabbrowser-tabbox:has(#tabbrowser-tabpanels[zen-split-view='true']) {
	--zen-element-separation: 8px !important;
}
```
</details>
