### ISSUE TITLE
Bookmarks in Toolbar disappearing when entering fullscreen

### ISSUE THREAD

**Issue by Psychosoc1al** [zen-browser/desktop#7042]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Reopening automatically closed #6318 in case @Jakllp won't as I have the same problem:

Bookmarks in toolbar disappear when going into fullscreen

Setup:

- Windows
- Multiple Toolbars or collapsed toolbars
- "Normal" mode (what's the opposite of compact?)
- All mods deactivated
- Background Gradient
- Some bookmarks in toolbar

Steps to reproduce:
- `F11` (aka fullscreen)
- Bookmarks gone

Normal mode and fullscreen:

![Image](https://github.com/user-attachments/assets/77abe5c1-ea44-409c-ba52-80d1172a72ed)

### Version

1.10.3t for me, originally 1.9b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Bookmarks

### Relevant log output if applicable

```shell

```

**Comment by jtbalk** [comment]
Same issue in linux - i3 on arch if it matters.

F11 -> bookmarks bar blank.

**Comment by BookCatKid** [comment]
Same issue here! Was about to go report this myself.
(on windows 11 btw)

**Comment by ydkcell** [comment]
Same on Windows, persists with all my profiles, as well as a newly created one.

**Comment by Waradu** [comment]
The issue seems to be in chrome://browser/skin/tabbrowser/fullscreen-and-pointerlock.css. `visibility: collapse;` makes it no longer visible.
```css
:root[inDOMFullscreen] #navigator-toolbox,
:root[inDOMFullscreen] #fullscr-toggler,
:root[inDOMFullscreen] #sidebar-box,
:root[inDOMFullscreen] #sidebar-main,
:root[inDOMFullscreen] #sidebar-splitter,
:root[inFullscreen]:not([macOSNativeFullscreen]) toolbar:not([fullscreentoolbar=true]):not(.zen-dont-hide-on-fullscreen),
:root[inFullscreen] .global-notificationbox {
  visibility: collapse;
}
```
This could be fixed by adding "fullscreentoolbar=true" or/and ".zen-dont-hide-on-fullscreen" to the toolbar. 
For now add this to userChrome.css to fix it:
```css
#PersonalToolbar {
  visibility: visible !important;
}
```
