### ISSUE TITLE
Address Bar shifts slightly when selecting part of the URL, changing the selection

### ISSUE THREAD

**Issue by Propheticus** [zen-browser/desktop#7586]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

In Zen it is currently impossible to correctly select a part of the URL upon first click+drag to select, because the popout shifts to the right slightly. The means the start of the selection suddenly shift 1 or 2 characters left.

Zen, selection is shifted left:

https://github.com/user-attachments/assets/38262954-12c6-4f2e-8aff-5a24d65f003c

Firefox, no selection issue:

https://github.com/user-attachments/assets/fa4e75e8-fad2-4891-b621-debe5597a439

### Version

1.11.2b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

URL Bar

### Relevant log output if applicable

```shell

```

**Comment by Propheticus** [comment]
This was reported before in https://github.com/zen-browser/desktop/issues/6065 which was closed in the great purge.

**Comment by sporocyst** [comment]
When urlbar selected:
* For .urlbar-input-container
`padding inline` changes from  `var(--urlbar-container-padding)` to `calc(var(--urlbar-margin-inline) + var(--urlbar-container-padding))`

* For #identity-box
`margin-right` changes  from `0 !important` to `var(--urlbar-margin-inline)`

These can be modified by CSS, but I am not sure if the result would fit @mauro-balades 's aesthetic sence. I'll just leave it there.

**Comment by Propheticus** [comment]
Fixed the issue for myself (only in the multiple toolbars layout) by putting this in _userChrome.css_

``` CSS
/* Fix the URL bar shift upon cursor click to allow accurate selection */
:root:not([zen-single-toolbar]) #urlbar[breakout][breakout-extend]:not([zen-floating-urlbar]) {
& > .urlbar-input-container {
    padding-inline: var(--urlbar-container-padding) !important;
    }
}

:root:not([zen-single-toolbar]) #urlbar[open]:not([zen-floating-urlbar]) {
 & #identity-box {
    margin-right: 0 !important;
    }
}
```

The `:not([zen-single-toolbar])` was added to leave the URL bar alone when it's the breakout from the single toolbar layout.

https://github.com/user-attachments/assets/dd93a7d6-4bbf-409e-afcf-3ab4737295c9

Optically doesn't change all that much, but saves a bit of frustration.
