### ISSUE TITLE
Compact-mode toolbox background visibly cuts off on wide/hires screens

### ISSUE THREAD

**Issue by kenblu24** [zen-browser/desktop#8408]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

![Image](https://github.com/user-attachments/assets/bdbe0303-6a1c-4702-ac5d-31bc1b5f40bd)

I think I've had this issue since around 1.11.3b, when a couple compact mode bug was fixed. I use Windows x64 usually but I repro'd this on Linux on a clean tarball install.

1. Open a clean install/profile of Zen and skip all the setup steps, including the color picker.
2. Set the toolbox to be on the right, and expand the toolbox width as far as possible to make this bug easier to see (approx 600px).
3. Enable compact mode option (right-click on toolbox empty area to see this option)
4. Set the workspace color (right-click -> Set Theme Color) to be a gradient, not a solid color.
5. On a monitor with a width > 2500px, drag the window to be wider than 2500px.
6. Show the toolbox by hovering over the right edge. You should be able to see the tiling of the gradient at around 2500px from the left window border.

I tested this on:
* 2560x1440 dual monitor on Windows 10, with OS scaling at 125%
* 2560x1080 single monitor on Ubuntu 24 x11, 100% scale

Possible lead
---
I found this :before in the inspector but changing it doesn't seem to change the tiling? Sorry, I know this probably isn't useful.
<details>

```css

  :root[zen-compact-mode="true"]:not([customizing]):not([inDOMFullscreen="true"]) {
    @media -moz-pref("zen.view.compact.hide-tabbar") or -moz-pref("zen.view.use-single-toolbar") {
      &:not([zen-compact-animating]) {
        & #navigator-toolbox:not([animate="true"]) #titlebar {
          &::before {
            @media -moz-pref("zen.view.compact.color-sidebar") {
              {
                background-color: !important;
                background-position-x: !important;
                background-position-y: !important;
                background-repeat: !important;
                background-image: !important;
                background-origin: !important;
                background-clip: !important;
                background-attachment: fixed !important;
                background-size: 2000px !important;
              }
            }
          }
        }
      }
    }
  }

```

</details>

### Version

1.12.5

### What platform are you seeing the problem on?

Linux (Tarball)

### What component is this issue related to?

Compact Mode

### Relevant log output if applicable

```shell

```
